runtime: go115

app_engine_apis: true

handlers:
  - url: /robots.txt
    static_files: robots.txt
    upload: robots.txt

  - url: /admin/.*
    script: auto
    secure: always
    login: admin

  - url: /webui/.*
    script: auto
    secure: always
    login: required

  - url: /.*
    script: auto
    secure: always

automatic_scaling:
  max_concurrent_requests: 80
  min_instances: 1
  max_instances: 1
