runtime: go111

handlers:
  - url: /admin/.*
    script: auto
    secure: always
    login: admin

  - url: /.*
    script: auto
    secure: always

automatic_scaling:
  max_concurrent_requests: 80
  min_instances: 1
